######################################################################
# Automatically generated by qmake (2.01a) Pzt Haz 28 08:34:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qprocess1.cpp
