Import("env")

obj=env.kobject("program")
obj.target='knazar'

obj.source="""
    main.cpp
    knazar.cpp 
    knazarballoon.cpp 
    knazardcop.skel
""" 

obj.libs="qt-mt kio kdecore"
obj.execute()

env.KDEinstall("KDEMENU", "Utilities", "knazar.desktop")
