#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import shutil
from optparse import OptionParser

i18n_languages = ["tr","nl","it","fr","de","pt_BR","es","pl","ca","sv"]
i18n_domain = "yali4"

def install(path):
    os.system("python %s/setup.py install" % path)

def copy(path):
    imagedir = os.path.join(path, "image")
    if os.path.exists("/usr/share/yali4"):
        print "Copying YALI test files into %s" % imagedir
    else:
        print "YALI test files not found!"

    os.system("/usr/bin/gcc desktop/yali-live.c -o %s/home/pars/.yali-live" % imagedir)
    os.system("/bin/chmod a+s %s/home/pars/.yali-live" % imagedir)
    os.system("/bin/mkdir -p %s/home/pars/Desktop" %imagedir)
    os.system("/bin/cp desktop/yali-live-installer.desktop %s/home/pars/Desktop/" %imagedir)
    os.system("/bin/cp -PR /usr/share/yali4 %s/usr/share/" % imagedir)
    os.system("/bin/cp -PR /usr/lib/python2.6/site-packages/yali4 %s/usr/lib/python2.6/site-packages/" % imagedir)
    os.system("/bin/cp /usr/bin/start-yali4 %s/usr/bin/start-yali4" % imagedir)



    for lang in i18n_languages:
            destpath = os.path.join(imagedir, "usr/share/locale/%s/LC_MESSAGES/yali4.mo" % lang)
            srcpath = os.path.join("/", "usr/share/locale/%s/LC_MESSAGES/yali4.mo" % lang)
            try:
                os.makedirs(destpath)
            except:
                pass
            print "cp /usr/share/locale/%s/LC_MESSAGES/yali4.mo %s " % (lang, os.path.join(imagedir, "usr/share/locale/%s/LC_MESSAGES/yali4.mo" % lang))
            shutil.copy(srcpath, destpath)

def main():
    #usage = "usage: %prog [options] arg"
    #parser = OptionParser(usage)
    parser = OptionParser()
    parser.add_option("-i", "--install", dest="install", metavar="/path/to/YALI",
            help="Build & Install YALI")
    parser.add_option("-o", "--only", dest="only", action="store_true",
            help="Skip Image Packages redownload")
    parser.add_option("-w", "--workdir", dest="workdir", metavar="WORKDIR",
            help="Pardusman workdir to make iso files")
    parser.add_option("-f", "--projectfile", dest="projectfile", metavar="FILE",
            help="Pardusman project file")
    parser.add_option("-p", "--pardusman", dest="pardusman", metavar="/path/to/PARDUSMAN",
            help="Pardusman Path")
    (opts, args) = parser.parse_args()

    if args :
        parser.error("incorrect number of arguments...")
    elif not opts.pardusman:
        opts.pardusman = os.getcwd()

    if opts.install:
        install(opts.install)
    else:
        install(os.getcwd())
        print "Using YALI in existing path"

    if opts.workdir and opts.only:
        os.system("python %s make-repo %s" % (opts.pardusman, opts.projectfile))
        os.system("python %s make-live %s" % (opts.pardusman, opts.projectfile))
    copy(opts.workdir)
    os.system("python %s pack-live %s" % (opts.pardusman, opts.projectfile))
    os.system("python %s make-iso %s" % (opts.pardusman, opts.projectfile))

if __name__ == "__main__":
    main()
