--- client/Makefile.orig	2008-03-08 19:57:57.000000000 +0200
+++ client/Makefile	2008-08-29 11:16:29.000000000 +0300
@@ -67,7 +67,6 @@
 	chmod +x $(DATADIR)/$(NAME)/client/*Profile.py
 	chmod +x $(DATADIR)/$(NAME)/client/smoltGui.py
 	
-	desktop-file-install --vendor='fedora' --dir=$(DATADIR)/applications ./smolt.desktop
 	
 move-mo: $(DIRED_MO_FILES)
 	
