Import("env")

obj=env.kobject("shlib")
obj.target='kwin3_tulliana'

obj.source="""
    tulliana.cpp
    tullianabutton.cpp
    tullianaclient.cpp
""" 

obj.libs="kdecore"
obj.execute()

env.KDEinstall("KDEDATA", "kwin", "tulliana.desktop")
