Import("env")

obj=env.kobject("program")
obj.target='kbeddua'

obj.source="""
    main.cpp
    kbeddua.cpp 
    kbedduadcop.skel
""" 

obj.libs="qt-mt kio kdecore"
obj.execute()

env.KDEinstall("KDEMENU", "Utilities", "kbeddua.desktop")
