#!/bin/bash

# Extract all the po files from the pspecs.
# Usage: extract-all-languages <path_to_devel>

for i in $(<../LANGUAGES); do
    echo "Processing $i language.."
    ./pspec2po extract $1 $i ../po/$i.po
done

