#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
    Lider
"""

# Standard modules
import sys

# Qt4 modules
from PyQt4 import QtGui


def main():
    """
        Main function
    """
    app = QtGui.QApplication(sys.argv)

    from lider.formmain import FormMain
    win = FormMain(app)
    win.show()

    app.exec_()

if __name__ == "__main__":
    main()
