#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
    Ahenk software update tool
"""

import optparse
import os
import sys


def main():
    """
        Main function.
    """

    # Command line options
    parser = optparse.OptionParser()
    parser.add_option("-s", "--security", action="store_true", dest="security",
                      help="Install security updates only.")
    parser.add_option("-n", "--dry-run", action="store_true", dest="dryrun",
                      help="Do nothing, just tell.")
    #parser.add_option("-v", "--verbose", dest="verbose", action="store_true",
    #                  help="Verbose mode")
    (options, args) = parser.parse_args()

    # Only root can run that application
    if os.getuid() != 0:
        print "%s must be run as root." % sys.argv[0]
        sys.exit(1)

    if options.security:
        if options.dryrun:
            print "Installing security updates only."
        else:
            os.system("pisi upgrade pisi --yes-all")
            os.system("pisi upgrade --security-only --yes-all")
    else:
        if options.dryrun:
            print "Installing updates."
        else:
            os.system("pisi upgrade pisi --yes-all")
            os.system("pisi upgrade --yes-all")

if __name__ == "__main__":
    sys.exit(main())
