#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from main.ui on Mon Sep 14 14:03:59 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(369, 460)
        MainWidget.setWindowTitle("MainWidget")
        self.verticalLayout = QtGui.QVBoxLayout(MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameList = QtGui.QFrame(MainWidget)
        self.frameList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameList.setFrameShadow(QtGui.QFrame.Raised)
        self.frameList.setObjectName("frameList")
        self.gridLayout_2 = QtGui.QGridLayout(self.frameList)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushNew = QtGui.QToolButton(self.frameList)
        self.pushNew.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.pushNew.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pushNew.setArrowType(QtCore.Qt.NoArrow)
        self.pushNew.setObjectName("pushNew")
        self.horizontalLayout_3.addWidget(self.pushNew)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.listItems = QtGui.QListWidget(self.frameList)
        self.listItems.setObjectName("listItems")
        self.gridLayout_2.addWidget(self.listItems, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frameList)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        self.pushNew.setText(kdecore.i18n("Find Services"))

