/*
  Copyright (c) 2005-2006, TUBITAK/UEKAE

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Please read the COPYING file.
*/

#include <ksimpleconfig.h>
#include <qlistbox.h>
#include <qradiobutton.h>
#include <qbuttongroup.h>
#include <qstringlist.h>
#include <qcheckbox.h>
#include <qfile.h>

#include "tvconfig.h"

TvConfig::TvConfig( QWidget *parent)
    : TvConfigUI(parent)
{
    QStringList cardVendors, tunerVendors;

    cardsDB.getVendors(&cardVendors);
    tvVendor->clear();
    tvModel->clear();
    tvVendor->insertStringList(cardVendors);

    tunersDB.getVendors(&tunerVendors);
    tunerVendor->clear();
    tunerModel->clear();
    tunerVendor->insertStringList(tunerVendors);
}

TvConfig::~TvConfig()
{
}

void TvConfig::tunerVendorChanged()
{
    QString vendor = tunerVendor->currentText();
    QStringList models;

    tunersDB.getTuners(vendor, &models);
    tunerModel->clear();
    tunerModel->insertStringList(models);
}

void TvConfig::tvVendorChanged()
{
    QString vendor = tvVendor->currentText();
    QStringList models;

    cardsDB.getCards(vendor, &models);
    tvModel->clear();
    tvModel->insertStringList(models);
    tvModel->sort();
}

void TvConfig::selectCard(int card_id)
{
    setCard(card_id);
}


void TvConfig::selectTuner(int tuner_id)
{
    setTuner(tuner_id);
}

int TvConfig::getCard()
{
    return cardsDB.getCard(tvModel->currentText());
}

void TvConfig::setCard(int card_id)
{
    QString vendor_name, card_name;
    QListBoxItem *item;

    cardsDB.getCard(card_id, BTTV, vendor_name, card_name);

    item = tvVendor->findItem(vendor_name);
    if (item) {
	tvVendor->setCurrentItem(item);
	tvVendorChanged();

	item = tvModel->findItem(card_name);
	if (item)
	    tvModel->setCurrentItem(item);
    }
}

int TvConfig::getTuner()
{
    return tunersDB.getTuner(tunerModel->currentText());
}


void TvConfig::setTuner(int tuner_id)
{
    QString vendor_name, tuner_name;
    QListBoxItem *item;

    tunersDB.getTuner(tuner_id, vendor_name, tuner_name);

    item = tunerVendor->findItem(vendor_name);
    if (item) {
	tunerVendor->setCurrentItem(item);
	tunerVendorChanged();

	item = tunerModel->findItem(tuner_name);
	if (item)
	    tunerModel->setCurrentItem(item);
    }
}

void TvConfig::saveOptions()
{
    int card, tuner, pll, radio = 0;

    KConfig *config = new KConfig("kcmtasmatvrc");
    QFile bttv("/etc/modules.d/bttv");

    card = getCard();
    tuner = getTuner();
    pll = pllGroup->id(pllGroup->selected());

    if (radioCard->isChecked())
	radio = 1;

    if (bttv.open(IO_WriteOnly | IO_Truncate)) {
	QTextStream os(&bttv);

	config->setFileWriteMode(0644);
	config->setGroup("System");
	config->writeEntry("Card", card);
	config->writeEntry("Tuner", tuner);
	config->writeEntry("Pll", pll);
	config->writeEntry("Radio", radio);
	config->sync();

	os << "### This file is automatically generated by tasma." << endl;
	os << "#" << endl;
	os << "# Please do not edit this file directly. All changes" << endl;
	os << "# made in this file will be lost." << endl;
	os << "#" << endl;
	os << endl;
	os << "options bttv card=" << card;

	if (tuner != AUTO_TUNER)
	    os << " " << "tuner=" << tuner;
	if (pll)
	    os << " " << "pll=" << pll;
	if (radio)
	    os << " " << "radio=" << radio;

	os << endl;

	bttv.close();
	system("/sbin/modules-update");
    }

    delete config;
}

// TODO: read dmesg for error or success
void TvConfig::removeModule()
{
    //FIXME: be smart, don't cheat you lazy $%@#!*
    QCString cmd = "/sbin/rmmod bt878 bttv";
    system(cmd);
}

// TODO: read dmesg for error or success
void TvConfig::loadModule()
{
    QCString cmd;
    int card, tuner, pll, radio = 0;

    card  = getCard();
    tuner = getTuner();
    pll   = pllGroup->id(pllGroup->selected());

    if (radioCard->isChecked())
	radio = 1;

    if (tuner != AUTO_TUNER)
	cmd.sprintf("/sbin/modprobe bttv card=%d tuner=%d pll=%d radio=%d", card, tuner, pll, radio);
    else
	cmd.sprintf("/sbin/modprobe bttv card=%d pll=%d radio=%d", card, pll, radio);

    system(cmd);
}

#include "tvconfig.moc"
