#!/usr/bin/python

## Load the builders
env = Environment( tools = ["default", "generic", "kde"], toolpath = ["./admin"])

# Set the build directory so we can do "rm -rf build" to clean up.
BuildDir("build/src", "src")

env.KDEuse("environ")

# target processing is done in the subdirectories
env.subdirs("build/src")

# CONVENIENCE FUNCTIONS TO EMULATE "make dist" and "make distclean"
env.dist("tulliana")
