#!/bin/bash
#
# TUBITAK UEKAE ~ Pardus Linux
# Copyright (C) 2011
# Mehmet Emre Atasever <memre ~ pardus.org.tr>
#
# pkg-config wrapper for PARM sb2 cross-build
#########################################################################
#
# Buildsystems often calls pkg-config for proper flags of the libraries.
# But pkg-config gives flags for native systems and cross-build fails
# because of linking x86 ELFCLASS. So we had to do a workaround like this.
#
# In order to use this script, copy this into the toolchain bin directory
# and add this bin directory at the head of the PATH variable
#
# if $SYSROOT variable is exported and --cflags --libs or --variable parametter
# is passed to the pkg-config, this script adds $SYSROOT to the flags.
#
# Example output:
#
# $ cp pkg-config /var/cross/sysroots/armv7l/bin
# $ PATH=/var/cross/sysroots/armv7l/bin:$PATH
# $ which pkg-config
# /opt/toolchain/armv7l/bin/pkg-config
# $ pkg-config --cflags --libs xrender
# -lXrender -lX11
# $ SYSROOT=/var/cross/sysroots/armv7l pkg-config --cflags --libs xrender
# -I/var/cross/sysroots/armv7l/usr/include  -L/var/cross/sysroots/armv7l/usr/lib -lXrender -lX11
#

args=
requires_cross_fix=false

while [ x"$1" != x"" ]; do
    args="${args} $1"

    case "$1" in
        --cflags*|--libs*|--variable*)
            requires_cross_fix=true
            ;;
    esac
    shift
done

${requires_cross_fix} && {
    if ! [ -z "$SYSROOT" ]; then
        args="${args} --define-variable=prefix=${SYSROOT}/usr --define-variable=exec_prefix=${SYSROOT}/usr"
    fi
}

# echo "args= \"$args\""
exec /usr/bin/pkg-config $args

