#!/bin/sh

#./hav.py register ati_drivers System.Service services/ati_drivers.py
#./hav.py register lirc System.Service services/lirc.py
#./hav.py register slmodem System.Service services/slmodem.py
#./hav.py register hsfmodem System.Service services/hsfmodem.py
#./hav.py register eciadsl System.Service services/eciadsl.py
#./hav.py register hcfpcimodem System.Service services/hcfpcimodem.py
./hav.py register vixie_cron System.Service services/vixie_cron.py
#./hav.py register git System.Service services/git.py
#./hav.py register subversion System.Service services/subversion.py
./hav.py register openssh System.Service services/openssh.py
#./hav.py register kexec_tools System.Service services/kexec_tools.py
./hav.py register sysklogd System.Service services/sysklogd.py
#./hav.py register yali System.Service services/yali.py
#./hav.py register xen System.Service services/xen.py
#./hav.py register nfs_utils System.Service services/nfs_utils.py
#./hav.py register gkrellm System.Service services/gkrellm.py
#./hav.py register irqbalance System.Service services/irqbalance.py
#./hav.py register acct System.Service services/acct.py
#./hav.py register acpid System.Service services/acpid.py
#./hav.py register apmd System.Service services/apmd.py
#./hav.py register nut System.Service services/nut.py
#./hav.py register pcsc_lite System.Service services/pcsc_lite.py
#./hav.py register rsync System.Service services/rsync.py
#./hav.py register ntlmaps System.Service services/ntlmaps.py
#./hav.py register mDNSResponder System.Service services/mDNSResponder.py
./hav.py register wpa_supplicant System.Service services/wpa_supplicant.py
./hav.py register cups System.Service services/cups.py
./hav.py register hplip System.Service services/hplip.py
#./hav.py register timidity System.Service services/timidity.py
#./hav.py register esound System.Service services/esound.py
#./hav.py register nas System.Service services/nas.py
#./hav.py register microcode_ctl System.Service services/microcode_ctl.py
#./hav.py register gpm System.Service services/gpm.py
#./hav.py register irda_utils System.Service services/irda_utils.py
#./hav.py register setserial System.Service services/setserial.py
#./hav.py register fnfx System.Service services/fnfx.py
#./hav.py register cyrus_sasl System.Service services/cyrus_sasl.py
#./hav.py register openct System.Service services/openct.py
#./hav.py register mdadm System.Service services/mdadm.py
#./hav.py register audit System.Service services/audit.py
#./hav.py register clamav System.Service services/clamav.py
#./hav.py register nessus System.Service services/nessus.py
#./hav.py register trousers System.Service services/trousers.py
./hav.py register portmap System.Service services/portmap.py
#./hav.py register ptsp_client System.Service services/ptsp_client.py
#./hav.py register postfix System.Service services/postfix.py
#./hav.py register dovecot System.Service services/dovecot.py
./hav.py register samba System.Service services/samba.py
#./hav.py register postgresql System.Service services/postgresql.py
./hav.py register mysql System.Service services/mysql.py
#./hav.py register firebird System.Service services/firebird.py
./hav.py register apache System.Service services/apache.py
#./hav.py register vsftpd System.Service services/vsftpd.py
#./hav.py register ypbind System.Service services/ypbind.py
#./hav.py register ypserv System.Service services/ypserv.py
#./hav.py register xinetd System.Service services/xinetd.py
#./hav.py register hylafax System.Service services/hylafax.py
#./hav.py register tftp System.Service services/tftp.py
#./hav.py register dhcp System.Service services/dhcp.py
#./hav.py register ntp System.Service services/ntp.py
#./hav.py register bind System.Service services/bind.py
#./hav.py register squid System.Service services/squid.py
#./hav.py register dansguardian System.Service services/dansguardian.py
#./hav.py register ejabberd System.Service services/ejabberd.py
#./hav.py register ltspfsd System.Service services/ltspfsd.py
#./hav.py register lbuscd System.Service services/lbuscd.py
#./hav.py register memcached System.Service services/memcached.py
./hav.py register kdebase System.Service services/kdebase.py
./hav.py register hal System.Service services/hal.py
#./hav.py register ipw3945_daemon System.Service services/ipw3945_daemon.py
#./hav.py register bluez_utils System.Service services/bluez_utils.py
#./hav.py register zemberek_server System.Service services/zemberek_server.py
