#!/usr/bin/python

env = Environment(CPPPATH = ["../include"], LIBPATH = ["../src"], LIBS = ["iksemelpp", "gc", "gccpp"])

conf = Configure(env)

if conf.CheckCHeader("errno.h"):
    conf.env.Append(CCFLAGS = "-DHAVE_ERRNO_H")

if conf.CheckCHeader("stdlib.h") and conf.CheckCHeader("string.h") and conf.CheckCHeader("stdarg.h"):
    conf.env.Append(CCFLAGS = "-DSTDC_HEADERS")

if conf.CheckCHeader("unistd.h"):
    conf.env.Append(CCFLAGS = "-DHAVE_ERRNO_H")

if conf.CheckCHeader("gc/gc.h"):
    conf.env.Append(CCFLAGS = "-DHAVE_GC")

env = conf.Finish()

Export('env')

SConscript(["src/SConscript", "examples/SConscript"])
