all:
	./ahenk_schema 1 softwarePolicy schema_templates/software.txt > schema/ahenk_software.schema
	./ahenk_schema 2 authenticationPolicy schema_templates/authentication.txt > schema/ahenk_authentication.schema
	./ahenk_schema 3 firewallPolicy schema_templates/firewall.txt > schema/ahenk_firewall.schema
	./ahenk_schema 4 apachePolicy schema_templates/apache.txt > schema/ahenk_apache.schema
