pyuic4 cd.ui -o cd.py
pyuic4 configuration.ui -o configuration.py
pyuic4 downloading.ui -o downloading.py
pyuic4 installing.ui -o installing.py
pyuic4 installing.ui -o installing.py
pyuic4 internet.ui -o internet.py
pyuic4 iso.ui -o iso.py
pyuic4 main.ui -o main.py
pyuic4 source.ui -o source.py
pyuic4 usb.ui -o usb.py
pyuic4 welcome.ui -o welcome.py
pyuic4 finish.ui -o finish.py
