#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys

import parsetasks

if len(sys.argv) != 2:
    print "Usage: show tasksfile"
    sys.exit(1)

parsetasks.parseTasksAndGenerateHtml(sys.argv[1])
os.system("konqueror %s.html" % sys.argv[1])
