#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import subprocess

COMMANDS_NOPARAM = [
                        "init",
                        "up",
                        "run",
                        "missing",
                   ]

COMMANDS_WITH_ONEPARAM = []

def usage():
    print """\
Pardus buildfarm framework

Usage: %s COMMAND
    Where COMMAND can be one of the following:

    init        Initializes a new buildfarm environment
    up          Checks out the repository from remote SCM
    run         Build and install packages
    missing     Dumps the packages which has releases not
                built yet.

    --version   Prints the version
""" % sys.argv[0]
    return 1

if __name__ == "__main__":
    # Dispatches commands to real commands
    if len(sys.argv) < 2:
        sys.exit(usage())

    cmd = sys.argv[1]

    # Handle the version in here for simplicity
    if cmd == "--version":
        import buildfarm
        print "Version: %s" % buildfarm.__version__

    elif cmd in COMMANDS_NOPARAM:
        sys.exit(subprocess.call(["buildfarm-%s" % cmd]))
    else:
        sys.exit(usage())

    sys.exit(0)
