
#!/usr/bin/env python
# Generated by pykdeuic4 from config.ui on Sun Jan 18 23:23:34 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_ServiceConfig(object):
    def setupUi(self, ServiceConfig):
        ServiceConfig.setObjectName("ServiceConfig")
        ServiceConfig.resize(400, 300)
        self.gridLayout = QtGui.QGridLayout(ServiceConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(ServiceConfig)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.serviceList = QtGui.QListWidget(ServiceConfig)
        self.serviceList.setObjectName("serviceList")
        self.gridLayout.addWidget(self.serviceList, 1, 0, 1, 2)
        self.showDesc = QtGui.QCheckBox(ServiceConfig)
        self.showDesc.setChecked(True)
        self.showDesc.setObjectName("showDesc")
        self.gridLayout.addWidget(self.showDesc, 2, 0, 1, 2)

        self.retranslateUi(ServiceConfig)
        QtCore.QMetaObject.connectSlotsByName(ServiceConfig)

    def retranslateUi(self, ServiceConfig):
        ServiceConfig.setWindowTitle(kdecore.i18n("System Services Configuration"))
        self.label.setText(kdecore.i18n("Select services to show in plasmoid."))
        self.showDesc.setText(kdecore.i18n("Show descriptions of services"))

