#!/bin/sh
# Copyright © 2005  TUBITAK/UEKAE
# Licensed under the GNU General Public License, version 2.
# See the file http://www.gnu.org/copyleft/gpl.txt.
#
# Original work belongs Gentoo Linux

# Contributed by Roy Marples (uberlord@gentoo.org)

exec /lib/rcscripts/net.modules.d/helpers.d/dhclient-udhcpc-wrapper ifconfig
